// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6F1qPn8SYh3a_aK48uzLI0EMjaDhEwGk',
    appId: '1:321501080252:web:9f31147ee8e8fc496f7eb9',
    messagingSenderId: '321501080252',
    projectId: 'fyp-database-dc27a',
    authDomain: 'fyp-database-dc27a.firebaseapp.com',
    storageBucket: 'fyp-database-dc27a.firebasestorage.app',
    measurementId: 'G-6NTY918SH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmUAT_Stl67Aq8f73wDX3Da1MEfOiH4_Y',
    appId: '1:321501080252:android:1a1075e8091711646f7eb9',
    messagingSenderId: '321501080252',
    projectId: 'fyp-database-dc27a',
    storageBucket: 'fyp-database-dc27a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDam6RUf3oF_6dUXkmHGgLms3F0xrs-21k',
    appId: '1:321501080252:ios:60e0cc6e1db79a776f7eb9',
    messagingSenderId: '321501080252',
    projectId: 'fyp-database-dc27a',
    storageBucket: 'fyp-database-dc27a.firebasestorage.app',
    iosBundleId: 'com.example.fypApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDam6RUf3oF_6dUXkmHGgLms3F0xrs-21k',
    appId: '1:321501080252:ios:60e0cc6e1db79a776f7eb9',
    messagingSenderId: '321501080252',
    projectId: 'fyp-database-dc27a',
    storageBucket: 'fyp-database-dc27a.firebasestorage.app',
    iosBundleId: 'com.example.fypApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6F1qPn8SYh3a_aK48uzLI0EMjaDhEwGk',
    appId: '1:321501080252:web:8aecd9a2d75b03256f7eb9',
    messagingSenderId: '321501080252',
    projectId: 'fyp-database-dc27a',
    authDomain: 'fyp-database-dc27a.firebaseapp.com',
    storageBucket: 'fyp-database-dc27a.firebasestorage.app',
    measurementId: 'G-1TR83452KH',
  );
}
